info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java-version: @java.version@
    encoding: @project.build.sourceEncoding@
    environment: ${spring.profiles.active}
    server-port: ${server.port}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.211:3306/test_config?useSSL=false
    username: test
    password: test@sxw
mybatis:
  config-location: classpath:mybatis.xml
debug: true
server:
  port: 8888
## Swagger configuration
swagger:
  enabled: true
  title: ${info.build.name}
  description: ${info.build.description}
  version: ${info.build.version}
  base-package: com.pjb.springbootjjwt.api
  base-path: /**
custom:
  ## token超时时间（毫秒）
  expireMillis: 1800000