info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java-version: @java.version@
    encoding: @project.build.sourceEncoding@
    environment: ${spring.profiles.active}
    server-port: ${server.port}
spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://localhost:3306/test?useunicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useunicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    #password: 123456
    password: root123
mybatis:
  mapper-locations: classpath:com/passion/ds/springboot/jwt/mapper/*Mapper.xml
  type-aliases-package: com.passion.ds.springboot.jwt.entity
#  config-location: classpath:mybatis.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Logger Config
logging:
  level:
    com.passion.ds.springboot.jwt: debug

#开起这项会输出starter各种信息
#debug: true
server:
  port: 8801
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8192
## Swagger configuration
swagger:
  enabled: true
  title: ${info.build.name}
  description: ${info.build.description}
  version: ${info.build.version}
  base-package: com.passion.ds.springboot.jwt
  base-path: /**
custom:
  ## token超时时间（毫秒）
  expireMillis: 1800000
config:
  token: false

